# Generated by Django 4.2.2 on 2023-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_location_alter_product_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
